-- CREATE DATABASE 
USE master
Go
	CREATE DATABASE BobsShoes;
Go

-- SHOE THE ENTRY FOR BobsShoes IN THE SYSTEM TABLES
SELECT * FROM sys.databases where name = 'BobsShoes';

-- SHOW THE LAYOUT OF THE FILES FOR THE DATABASE
USE BobsShoes 
GO
	EXEC sp_helpfile
GO

-- CREATE AN ORDER SCHEMA FOR BOBS ORDERS

CREATE SCHEMA Orders 
	AUTHORIZATION dbo
GO

-- DROP SCHEMA 
-- DROP SCHEMA Orders;

-- CREATE NEW FILEGROUP FOR THE DATA AND LOGS
ALTER DATABASE BobsShoes 
	ADD FILEGROUP BobsData;

ALTER DATABASE BobsShoes 
	ADD FILE (
		NAME = BobsShoes,
		FILENAME = 'C:\Users\mdabd\BobsShoes.mdf'
	)
	TO FILEGROUP BobsData;

ALTER DATABASE BobsShoes 
	ADD LOG FILE (
		NAME = BobsShoes_log,
		FILENAME = 'C:\Users\mdabd\BobsShoes_log.ldf'
	);
GO







